require('./src/styles/animate.css')
require('./src/styles/icomoon.css')
require('./src/styles/bootstrap.css')
require('./src/styles/flexslider.css')
require('./src/styles/style.css')
require('./src/styles/mods.css')